### create user
POST http://localhost:3000/users/create
content-type: application/json

{
  "name": "mohamed"
}

### get all users
GET http://localhost:3000/users

### get ptricular user
GET http://localhost:3000/users/5

### Update user
PATCH http://localhost:3000/users/5
content-type: application/json

{
  "name": "leen"
}

### Delete user
DELETE http://localhost:3000/users/6
