### create user
POST http://localhost:3000/users
content-type: application/json

{
  "name": "asma"
}

### get all users
GET http://localhost:3000/users

### get ptricular user
GET http://localhost:3000/users/5

### Update user
PATCH http://localhost:3000/users/4
content-type: application/json

{
  "name": "ghada"
}

### Delete user
DELETE http://localhost:3000/users/6
