### Create Discount Card (percentile,flat)
POST http://localhost:3000/discount-card
Content-Type: application/json

{
  "discountType": "per", 
  "discountValue": 50,
  "expirationDurationMinutes": 10
}

### Get All Discount Cards
GET http://localhost:3000/discount-card

### Get Discount Card by Code (For test)
GET http://localhost:3000/discount-card/code?code=5qAbTPgeOHtmUUfF

### Get Particular Discount Card
GET http://localhost:3000/discount-card/25

### Update Discount Card
PATCH http://localhost:3000/discount-card/33
Content-Type: application/json

{
  "code": "deyaaloveu",
  "discountType": "per",
  "discountValue": 100,
  "expirationDurationMinutes": 10
}

### Delete Discount Card
DELETE http://localhost:3000/discount-card/25