
export const RATE_LIMIT_WINDOW_SECONDS = 60;
export const RATE_LIMIT_WINDOW_MS = RATE_LIMIT_WINDOW_SECONDS * 1000;


export const RATE_LIMIT_MAX_FAILED_ATTEMPTS = 5;

export const RATE_LIMIT_LAST_ALLOWED_FAILURE_OFFSET = RATE_LIMIT_MAX_FAILED_ATTEMPTS - 1;
