### create product
POST http://localhost:3000/products
Content-Type: application/json

{
  "name": "sai",
  "price": 100
}

### get all products
GET http://localhost:3000/products

### get particular product
GET http://localhost:3000/products/6

### Update product
PATCH http://localhost:3000/products/7
Content-Type: application/json

{
  "name": "love",
  "price": 50
}

### Delete product
DELETE http://localhost:3000/products/8